# 1. IDENTITÉ DU PROJET
owner: DimGTHUB
repo: Statuts-de-mes-outils

# 2. VOS SITES (Avec les nouveaux noms)
sites:
  - name: "📂 Outils : Wrike"
    url: https://www.wrike.com/

  - name: "🏭 Métier : Lomaco Régulation"
    url: https://keolis.mycaelis.fr/regulation/

  - name: "🏭 Métier : Lomaco Gestion Temps"
    url: https://keolisgdt.mycaelis.fr/gestiondutemps/
    expectedStatusCodes: [200, 201, 404]

  - name: "🏭 Métier : Kopilot"
    url: https://prod.kopilot.apps.localsolver.com/login

# 3. CONFIGURATION DU SITE WEB
status-website:
  theme: dark
  logoUrl: https://raw.githubusercontent.com/DimGTHUB/Statuts-de-mes-outils/master/Keolis_Sante-removebg-preview.png
  name: Météo des services
  introTitle: "**État de fonctionnement**"
  introMessage: "Bienvenue sur la page de statut de nos outils."
  baseUrl: /Statuts-de-mes-outils
  
  # C'est cette partie "navbar" qui manquait probablement et faisait planter le robot :
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# 4. TRADUCTION (Aligné tout à gauche)
i18n:
  activeIncidents: "Incidents en cours"
  allSystemsOperational: "Tous les systèmes sont opérationnels"
  incidentReport: "Rapport d'incident"
  latestIncidents: "Derniers incidents"
  notice: "Note de maintenance"
  overallUptime: "Disponibilité globale"
  averageResponseTime: "Temps de réponse moyen"
  url: "Lien"
  status: "État"
  history: "Historique"
  uptime: "Disponibilité"
  responseTime: "Réponse"
  # Unités de temps
  ms: "ms"
  seconds: "s"
  minutes: "min"
  hours: "h"
  days: "j"
  weeks: "sem"
  months: "mo"
  years: "ans"
  second: "s"
  minute: "min"
  hour: "h"
  day: "j"
