# Configuration de base
owner: DimGTHUB
repo: Statuts-de-mes-outils

sites:
  - name: Wrike
    url: https://www.wrike.com/
  - name: Lomaco Online - Régulation
    url: https://keolis.mycaelis.fr/regulation/
  - name: Lomaco Online - Gestion du Temps
    url: https://keolisgdt.mycaelis.fr/gestiondutemps/
    expectedStatusCodes: [200, 201, 404]
  - name: KS SLV - Clisson
    url: 185.15.26.36
    check: "tcp-ping"
    port: 443

status-website:
  # 1. LE DESIGN GLOBAL
  # Mettez 'light' pour fond blanc ou 'dark' pour fond noir
  theme: light 
  
  # 2. VOTRE LOGO
  # Remplacez le lien ci-dessous par celui de VOTRE logo (copié depuis votre site)
  # Si vous n'en avez pas, laissez la ligne vide ou mettez un # devant
  logoUrl: https://github.com/DimGTHUB/Statuts-de-mes-outils/blob/fb28fadce07334a750d1088101403581dba9fb13/Keolis_Sante-removebg-preview.png

  # 3. VOS TEXTES (C'est ici qu'on enlève le blabla en anglais)
  name: Météo des services
  introTitle: "**État de fonctionnement**"
  introMessage: "Bienvenue sur la page de statut de nos outils. Vous trouverez ici l'état de nos services en temps réel."
  
  # Configuration technique du site (ne pas toucher)
  baseUrl: /Statuts-de-mes-outils
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
