# Collez ceci tout en bas du fichier, aligné tout à gauche
i18n:
  # --- Les textes principaux (qui marchent déjà) ---
  activeIncidents: "Incidents en cours"
  allSystemsOperational: "Tous les systèmes sont opérationnels"
  incidentReport: "Rapport d'incident"
  latestIncidents: "Derniers incidents"
  notice: "Note de maintenance"
  overallUptime: "Disponibilité globale"
  averageResponseTime: "Temps de réponse moyen"
  url: "Lien"
  status: "État"
  history: "Historique"
  uptime: "Disponibilité"
  responseTime: "Réponse"
  
  # --- LE BAZOOKA DES UNITÉS DE TEMPS ---
  # On met toutes les variantes possibles pour tuer le "undefined"
  
  # Variantes courtes
  ms: "ms"
  s: "s"
  m: "min"
  h: "h"
  d: "j"
  
  # Variantes longues singulier
  second: "s"
  minute: "min"
  hour: "h"
  day: "j"
  week: "sem"
  month: "mois"
  year: "an"
  
  # Variantes longues pluriel
  seconds: "s"
  minutes: "min"
  hours: "h"
  days: "j"
  weeks: "sem"
  months: "mois"
  years: "ans"

  # Variantes techniques "timeX"
  timeMs: "ms"
  timeSecond: "s"
  timeSeconds: "s"
  timeMinute: "min"
  timeMinutes: "min"
  timeHour: "h"
  timeHours: "h"
  timeDay: "j"
  timeDays: "j"
  timeWeek: "sem"
  timeWeeks: "sem"
  timeMonth: "mois"
  timeMonths: "mois"
  timeYear: "an"
  timeYears: "ans"
  
  # Variantes "durationX" (parfois utilisées)
  durationMs: "ms"
  durationSecond: "s"
  durationSeconds: "s"
  durationMinute: "min"
  durationMinutes: "min"
