owner: DimGTHUB
repo: Statuts-de-mes-outils

sites:
  - name: Wrike
    url: https://www.wrike.com/
    group: Outils

  - name: Lomaco Online - Régulation
    url: https://keolis.mycaelis.fr/regulation/
    group: Application Métier

  - name: Lomaco Online - Gestion du Temps
    url: https://keolisgdt.mycaelis.fr/gestiondutemps/
    expectedStatusCodes: [200, 201, 404]
    group: Application Métier

  - name: Kopilot
    url: https://prod.kopilot.apps.localsolver.com/login
    group: Application Métier

status-website:
  theme: dark
  
  logoUrl: https://raw.githubusercontent.com/DimGTHUB/Statuts-de-mes-outils/master/Keolis_Sante-removebg-preview.png

  name: Météo des services
  introTitle: "**État de fonctionnement**"
  introMessage: "Bienvenue sur la page de statut de nos outils. Vous trouverez ici l'état de nos services en temps réel."
  
  baseUrl: /Statuts-de-mes-outils
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
