# Change these first
owner: DimGTHUB # Your GitHub organization or username, where this repository lives
repo: statut-de-mes-outils # The name of this repository

sites:
  - name: Wrike
    url: https://www.wrike.com/
  - name: Lomaco Online - Régulation
    url: https://keolis.mycaelis.fr/regulation/
  - name: Lomaco Online - Gestion du Temps
    url: https://keolisgdt.mycaelis.fr/gestiondutemps/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /statut-de-mes-outils
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: Voici l'état de fonctionnement de nos applications en temps réel.
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
