# Configuration
owner: DimGTHUB
repo: Statuts-de-mes-outils

sites:
  - name: "📂 Outils : Wrike"
    url: https://www.wrike.com/

  - name: "🏭 Métier : Lomaco Régulation"
    url: https://keolis.mycaelis.fr/regulation/

  - name: "🏭 Métier : Lomaco Gestion Temps"
    url: https://keolisgdt.mycaelis.fr/gestiondutemps/
    expectedStatusCodes: [200, 201, 404]

  - name: "🏭 Métier : Kopilot"
    url: https://prod.kopilot.apps.localsolver.com/login

status-website:
  theme: dark
  logoUrl: https://raw.githubusercontent.com/DimGTHUB/Statuts-de-mes-outils/master/Keolis_Sante-removebg-preview.png
  name: Météo des services
  introTitle: "**État de fonctionnement**"
  introMessage: "Bienvenue sur la page de statut de nos outils. Vous trouverez ici l'état de nos services en temps réel."
  baseUrl: /Statuts-de-mes-outils
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  activeIncidents: "Incidents en cours"
  allSystemsOperational: "Tous les systèmes sont opérationnels"
  incidentReport: "Rapport d'incident"
  latestIncidents: "Derniers incidents"
  notice: "Note de maintenance"
  overallUptime: "Disponibilité globale"
  averageResponseTime: "Temps de réponse moyen"
  url: "Lien"
  status: "État"
  history: "Historique"
  uptime: "Disponibilité"
  responseTime: "Réponse"
  ms: "ms"
  second: "seconde"
  seconds: "s"
  minute: "minute"
  minutes: "min"
  hour: "heure"
  hours: "h"
  day: "jour"
  days: "j"
  week: "semaine"
  weeks: "sem"
  month: "mois"
  months: "mo"
  year: "an"
  years: "ans"
  
  # Variantes
  timeSeconds: "s"
  timeMinutes: "min"
  timeHours: "h"
  timeDays: "j"
